feat: Add new proxy contract
chelofinance/Xion-hackton pull request #70
Opened 2024-02-19 01:15 UTC by kmchmk

2024-02-19 10:45 UTC, isakfm approved these changes
Looks good

2024-02-20 02:35 UTC, rafaelChelo requested changes

2024-02-20 02:47 UTC, kmchmk commented on contracts/multisig/src/contract.rs
> +    fn validate_sender(info: &MessageInfo, cfg: &Config, sender: Option<Addr>) -> MessageInfo {
Actually the suggested `from` is the `sender` here.
There are 3 values.
1. cgf.proxy (Allowed proxy address)
2. sender (Sent in every msg. Same as the suggested `from`)
3. info.sender (The actual executor/signer)

The logic here is to validate the `info.sender` is equal to `cfg.proxy`.
Then assign the `sender` to `info.sender`

2024-02-20 09:18 UTC, kmchmk commented on contracts/proxy/src/contract.rs
> +    let cosmsg = CosmosMsg::Wasm(WasmMsg::Execute {
Added the new logic. However the new field is called `sender` instead of `from`.

2024-02-20 21:02 UTC, rafaelChelo commented
Well done @kmchmk !
Merging

2024-02-20 21:02 UTC, merged